### PR TITLE
Added InfoButton

### LINKED ISSUE #85: Feature to show shortcut keys

### PR DESCRIPTION
**Pull request by DivyeshPuri**
Fixes #85

### CODE REVIEW

**Comment by anshumanv** [comment]
Make UI Improvements

**Comment by aashutoshrathi** [comment]
I think svg should be used, check this one.
https://www.flaticon.com/free-icon/information_157933#term=info&page=1&position=9

**Comment by Monal5031** [comment]
Better use the fa icons or glyphicons?

**Comment by anshumanv** [comment]
Will look for a fa alternative from next time.

**Review by anshumanv — APPROVED** [review]
👍

**Pull request merged**
