### PR TITLE
functionality for closing the playlist menu without having to use the close button

### LINKED ISSUE #205: Side bar to close when user click out of side bar.
The side bar should close whenever user click anywhere but the side bar.
The close button to side bar is only available on top of the side bar. If user navigate or scroll to the bottom, the side bar can't be close except going back to the top and close it.

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This issue is for enhancement/bug fixing.
- [ ] This issue is an addition to JSON database.
- [x] I have gone through [Contribution Guidelines](https://github.com/anshumanv/ongaku/blob/master/CONTRIBUTING.md).
- [ ] Assign this issue to me.

### PR DESCRIPTION
**Pull request by joseph-perez**
Fixes #205 

#### This PR is for [Anime Name].

- [x] This issue is for enhancement/bug fixing.
- [ ] This issue is an addition to JSON database.
	- [ ] Pull Request Title is of form `Added [Anime Name]`.
- [ ] This addition is already on ongaku.
	- [ ] This PR is an improvement to current addition.
- [x] I have checked my addition locally and it is working and won't break existing entries.
- [x] I have gone through [Contribution Guidelines](https://github.com/anshumanv/ongaku/blob/master/CONTRIBUTING.md).
- [x] This pull request will be closed if I failed to update it even once in a week.

### CODE REVIEW

**Comment by joseph-perez** [comment]
The changes that it shows for the index.html file was just because there were merge conflicts that I fixed. So just some spacing was removed between html tags, nothing major. 😄

**Comment by anshumanv** [comment]
Hey, @joseph-perez it works flawlessly! 😄 
Perhaps a little favor that I have to ask, can you do the same thing for the preferences button since it has the same problem. One has to click the button, again and again, to toggle open/close.

**Comment by anshumanv** [comment]
Also try to not include older commits in a PR, use branches or refork when you wanna send a PR.

**Comment by joseph-perez** [comment]
Yup will do! And sure thing I'll start branching off on the fork I have from here on out for new issues

**Comment by anshumanv** [comment]
Thanks, please add commits for preferences button to this PR then I'll merge this.

**Review by anshumanv — APPROVED** [review]
Works Well. 👍

**Comment by anshumanv** [comment]
Thanks so much for this @joseph-perez 😄

**Comment by joseph-perez** [comment]
Yeah no prob at all! 😁

**Comment by anshumanv** [comment]
Also, I missed the test logging in the console, thanks for taking care of that as well.

**Pull request merged**
