### PR TITLE
Improve the current HTML Audio Player UI

### LINKED ISSUE #192: Improve the current HTML Audio Player UI
The current audio player is very primitive and has poor UI, there are so many better material custom HTML/CSS audio players available out there, we should port to them else the simple player at the top of the screen in http://openings.moe works well too.

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This issue is for enhancement/bug fixing.
- [ ] This issue is an addition to JSON database.
- [x] I have gone through [Contribution Guidelines](https://github.com/anshumanv/ongaku/blob/master/CONTRIBUTING.md).
- [ ] Assign this issue to me.

### PR DESCRIPTION
**Pull request by darrylsepeda**
Fixes #192 

#### This PR is for [Anime Name].

- [x] This issue is for enhancement fixing.
- [ ] This issue is an addition to JSON database.
	- [ ] Pull Request Title is of form `Added [Anime Name]`.
- [ ] This addition is already on ongaku.
	- [ ] This PR is an improvement to current addition.
- [x] I have checked my addition locally and it is working and won't break existing entries.
- [x] I have gone through [Contribution Guidelines](https://github.com/anshumanv/ongaku/blob/master/CONTRIBUTING.md).
- [x] This pull request will be closed if I failed to update it even once in a week.

### CODE REVIEW

**Comment by anshumanv** [comment]
Hey, thanks so much for this job @darrylsepeda!
I've been wanting someone to do this like since forever. 😄 
Lemme fix the build, then I'll merge. 👍

**Review by anshumanv — COMMENTED** [review]
The playlist and preferences button don't close on clicking the screen, please look into this.

**Comment by darrylsepeda** [comment]
fix for playlist, has been done in my PR #212 :)
I'll fix the preference button in that PR too

**Comment by darrylsepeda** [comment]
@anshumanv done, close function for preference has been added, please kindly check :)

**Comment by anshumanv** [comment]
Hey, @darrylsepeda I just checked it out locally and it works flawlessly.
Just one last thing before I merge, can you please look into why the transition animation of track-list is not working? Also thanks for the quick fix. 😄

**Comment by darrylsepeda** [comment]
Sorry, not realized that animation has gone.. Already fixed now 😄

**Comment by darrylsepeda** [comment]
btw @anshumanv, I'm still wondering why do u remove #200? because currently I can't check the name when it plays in the middle..

**Comment by anshumanv** [comment]
@darrylsepeda add transition when the tracklist is closing too, Your PR about #200 was good but I was thinking of something else, I'm planning to merge preferences button and keycode button in one place, where we can display song info, name etc. More like they have in http://openings.moe/
Let me know if you can send a PR for that. 😄

**Comment by anshumanv** [comment]
The menu that they have in http://openings.moe/ our preferences button should display that content.

**Comment by darrylsepeda** [comment]
Hahaha.. I thought the way animation works at closing is same with the way it works at opening. Now, everything works properly, please kindly check.

Okay I'll check that link first, but why do we following all of their design?

**Review by anshumanv — APPROVED** [review]
Perfect 👍

**Comment by anshumanv** [comment]
Haha yea @darrylsepeda, we won't if we can come up with something better. 😆

**Pull request merged**
