### PR TITLE
Enhanced Info bar

### LINKED ISSUE #167: InfoBar Enhancement
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This issue is for enhancement/bug fixing.
- [ ] This issue is an addition to JSON database.
- [x] I have gone through [Contribution Guidelines](https://github.com/Anshuman-Verma/ongaku/blob/master/CONTRIBUTING.md).
- [x] Assign this issue to me.

### PR DESCRIPTION
**Pull request by DivyeshPuri**
Fixes #167 

- [x] This issue is for enhancement/bug fixing.
- [ ] This issue is an addition to JSON database.
	- [ ] Pull Request Title is of form `Added [Anime Name]`.
- [x] This addition is already on ongaku.
	- [x] This PR is an improvement to current addition.
- [x] I have checked my addition locally and it is working and won't break existing entries.
- [x] I have gone through [Contribution Guidelines](https://github.com/Anshuman-Verma/ongaku/blob/master/CONTRIBUTING.md).
- [x] This pull request will be closed if I failed to update it even once in a week.

### CODE REVIEW

**Review by anshumanv — CHANGES_REQUESTED** [review]
Lessen the space between all fields, if needed reduce font size by one

**Comment by aashutoshrathi** [comment]
Why Travis is failing?

**Comment by anshumanv** [comment]
You should have a better idea @aashutoshrathi !

**Comment by aashutoshrathi** [comment]
Oh!, @Lucifer24 didn't update his branch with the latest Dead Link Fix I did.

**Comment by anshumanv** [comment]
Noob 👎

**Review by anshumanv — APPROVED** [review]

**Pull request merged**
