### PR TITLE
#182 sidebar feature added

### LINKED ISSUE #182: Left side-nav to display playlist
Need a button on the top-left clicking on which will unfold a sidenav which will contain the tracks in sequence to be played, clicking on any particular track will play it.

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This issue is for enhancement/bug fixing.
- [ ] This issue is an addition to JSON database.
- [x] I have gone through [Contribution Guidelines](https://github.com/Anshuman-Verma/ongaku/blob/master/CONTRIBUTING.md).
- [ ] Assign this issue to me.

### PR DESCRIPTION
**Pull request by vijaygomathinayagam**
Fixes #182 

#### This PR is for [Anime Name].

- [x] This issue is for enhancement/bug fixing.
- [ ] This issue is an addition to JSON database.
	- [ ] Pull Request Title is of form `Added [Anime Name]`.
- [ ] This addition is already on ongaku.
	- [ ] This PR is an improvement to current addition.
- [x] I have checked my addition locally and it is working and won't break existing entries.
- [x] I have gone through [Contribution Guidelines](https://github.com/Anshuman-Verma/ongaku/blob/master/CONTRIBUTING.md).
- [x] This pull request will be closed if I failed to update it even once in a week.

### CODE REVIEW

**Comment by anshumanv** [comment]
Thanks for your work @VijayGomathi 
Here are the changes we need :- 
* Name of the song is not correct sometimes.
* Song image is not needed in the side-nav, so let's remove that and narrow down the distance between song names.
* Let's make the side nav a bit transparent so it won't hide the image (personal preference).
* Need to filter out songs from side-nav on specifying a preference, i.e  only openings should be displayed in sidenav when openings are selected as the only preference.
* Make search more stable, it just starts playing something without clicking when i enter some letters, without selection.
* Selecting some other song plays some other song sometimes.
asd

**Comment by vijaygomathinayagam** [comment]
1. I am using song names from data.json so technically song names must be correct.
2,3,4. noted
5. Can you give me the case when it occurs
6. I will debug

**Comment by vijaygomathinayagam** [comment]
point 2&3 above are 5&6

**Comment by anshumanv** [comment]
Just type 'n' in the search bar and a random song will start playing, about the song name bug I meant when clicking some song from the nav the song name on which we click on ain't played and some other song starts playing (not always).

**Comment by anshumanv** [comment]
@VijayGomathi this PR has progressed slowly and #187 has implemented all the things I need, I appreciate your contribution to this but #187 get the things in place so I have merged that.

Also, I'll not mark this as `invalid` hence you will get your hacktoberfest credit.

**Comment by vijaygomathinayagam** [comment]
sorry I can't allocate more time on this. You can mark this "invalid". credits are not important for me.

**Pull request closed without merging**
