### PR TITLE
add font-awesome icons

### LINKED ISSUE #189: Migrate all icons to font-awesome
Currently, we're using various images as icons for different functionality. The icons tend to mix up sometimes with the background and aren't clearly visible. I'm thinking of porting all icons while maintaining their positions to use white fa icons with a black border, also on hovering over an icon, it should expand by say 5% or 10% and it should be slight gray filled in that case.

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This issue is for enhancement/bug fixing.
- [ ] This issue is an addition to JSON database.
- [x] I have gone through [Contribution Guidelines](https://github.com/anshumanv/ongaku/blob/master/CONTRIBUTING.md).
- [ ] Assign this issue to me.

### PR DESCRIPTION
**Pull request by darrylsepeda**
Fixes #189 

#### This PR is for [Anime Name].

- [x] This issue is for enhancement/bug fixing.
- [ ] This issue is an addition to JSON database.
	- [ ] Pull Request Title is of form `Added [Anime Name]`.
- [ ] This addition is already on ongaku.
	- [ ] This PR is an improvement to current addition.
- [x] I have checked my addition locally and it is working and won't break existing entries.
- [x] I have gone through [Contribution Guidelines](https://github.com/anshumanv/ongaku/blob/master/CONTRIBUTING.md).
- [x] This pull request will be closed if I failed to update it even once in a week.

### CODE REVIEW

**Review by anshumanv — COMMENTED** [review]
Can we rather use the CDN for importing fa instead of importing the whole file?

**Comment by darrylsepeda** [comment]
as you wish @anshumanv

**Comment by anshumanv** [comment]
Thanks, @darrylsepeda for the quick fixes. 😄 
Don't feel shy to star the repo. 😛

**Review by anshumanv — APPROVED** [review]
👍

**Pull request merged**
