### PR TITLE
Added Issue & PR Template

### LINKED ISSUE #108: Add Issue Template
Give various fields to show whether the issue is about adding new content or app updates.
And a checkbox to show if the user wanna work on it.
Please comment if any other useful thing can be included.

### PR DESCRIPTION
**Pull request by aashutoshrathi**
Fixes #108 
Do not merge till we add every necessary point.

### CODE REVIEW

**Comment by anshumanv** [comment]
Looks great !

**Comment by DivyeshPuri** [comment]
@aashutoshrathi  an option regarding better solution can be added

**Comment by Monal5031** [comment]
`not affecting other code` is important I guess here.

**Comment by anshumanv** [comment]
Add a check for when a user updates an image/song, make sure he uses a better alternative.

**Comment by aashutoshrathi** [comment]
Look I think we went far off the point here, this is Issue Template, not PR template. Let me make one PR Template too.

**Comment by aashutoshrathi** [comment]
@Anshuman-Verma @Monal5031 Check it now, I think it is GTG.

**Review by anshumanv — APPROVED** [review]
👍

**Pull request merged**
