### PR TITLE
Fix bottom-bar position on loading

### LINKED ISSUE #173: fix the position of bottom-bar
##### `bottom-bar` shows up in the middle when the page is initially loading.

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This issue is for enhancement/bug fixing.
- [ ] This issue is an addition to JSON database.
- [x] I have gone through [Contribution Guidelines](https://github.com/Anshuman-Verma/ongaku/blob/master/CONTRIBUTING.md).
- [ ] Assign this issue to me.

### PR DESCRIPTION
**Pull request by Sn0wFox**
Fixes #173

#### This PR is for [Anime Name].

- [x] This issue is for enhancement/bug fixing.
- [ ] This issue is an addition to JSON database.
	- [ ] Pull Request Title is of form `Added [Anime Name]`.
- [ ] This addition is already on ongaku.
	- [ ] This PR is an improvement to current addition.
- [x] I have checked my addition locally and it is working and won't break existing entries.
- [x] I have gone through [Contribution Guidelines](https://github.com/Anshuman-Verma/ongaku/blob/master/CONTRIBUTING.md).
- [x] This pull request will be closed if I failed to update it even once in a week.

### CODE REVIEW

**Comment by Sn0wFox** [comment]
Looks like a little piece of css did the trick.

**Comment by anshumanv** [comment]
Looks amazing !

**Review by anshumanv — APPROVED** [review]

**Comment by anshumanv** [comment]
@aashutoshrathi can you check why travis build is failing ?

**Comment by Sn0wFox** [comment]
@anshumanv I saw that you have a bad URL in your `data.json` line 1162 (on the `img` the file extension is `.jpgg`):

    {
		"link" : "http://67.159.62.2/anime_ost/fairy-tail-original-soundtrack-vol-1/tixatygzwn/08%20-%20Nigiyaka%20na%20Machi.mp3",
		"name" : "Fairy Tail OST - Nigiyaka na Machi",
		"img" : "https://i.ytimg.com/vi/n8a4f3QSowk/maxresdefault.jpgg"
    }

Not sure, but may be the root of the failing build problem.

**Comment by Monal5031** [comment]
yeah @Sn0wFox is correct, it is causing the build to fail.
@anshumanv try removing the `g` at end it will work then, if you are okay can I send a PR?

**Comment by anshumanv** [comment]
Sorry, my bad!
Thanks for the follow up @Sn0wFox 
@Monal5031 please do if @Sn0wFox is okay with it, since he is the one who picked that :stuck_out_tongue:

**Comment by Monal5031** [comment]
Yeah sure, finders keepers 👍 do tell @Sn0wFox if you are not doing it.

**Comment by Sn0wFox** [comment]
No problem, you guys can go ahead and fix it 👍

**Pull request merged**
