### PR TITLE
Added Macross Plus OP - Voices

### PR DESCRIPTION
**Pull request by Endless7188**
Contributes to Issue #195

#### This PR is for Macross Plus.

- [ ] This issue is for enhancement/bug fixing.
- [x] This issue is an addition to JSON database.
	- [x] Pull Request Title is of form `Added [Anime Name]`.
- [ ] This addition is already on ongaku.
	- [ ] This PR is an improvement to current addition.
- [x] I have checked my addition locally and it is working and won't break existing entries.
- [x] I have gone through [Contribution Guidelines](https://github.com/anshumanv/ongaku/blob/master/CONTRIBUTING.md).
- [ ] This pull request will be closed if I failed to update it even once in a week.

### CODE REVIEW

**Review by starkblaze01 — CHANGES_REQUESTED** [review]
The download link is not correct
and the wallpaper is too realistic doesn't match with actual anime graphics

**Comment by Endless7188** [comment]
The link is not working?  Interesting... 

I can get another wallpaper, but that is representative of the CGI scenes from the show.  I can change if necessary.  I'll have to see whats up with the link not working.

edit - I've checked that link and a handful of others and they seem to be downloading properly.

**Review by starkblaze01 — APPROVED** [review]
Changes looks good,
Link is working 
Image is perfect but it would be better if HD quality was used, it's getting little blurred when running on Ongaku.

**Comment by anshumanv** [comment]
Is it not possible to get a direct mp3 link? 
The link you gave is slow since it goes through the process of conversion to mp3.

**Pull request closed without merging**
