### PR TITLE
Added BnHA S2 OST-2

### PR DESCRIPTION
**Pull request by aulisius**
Is working towards #195. Technically, it can never be closed unless we make an exhaustive list of all animes.

#### This PR is for Boku no Hero Academia.

- [ ] This issue is for enhancement/bug fixing.
- [x] This issue is an addition to JSON database.
	- [x] Pull Request Title is of form `Added [Anime Name]`.
- [ ] This addition is already on ongaku.
	- [ ] This PR is an improvement to current addition.
- [ ] I have checked my addition locally and it is working and won't break existing entries.
- [x] I have gone through [Contribution Guidelines](https://github.com/anshumanv/ongaku/blob/master/CONTRIBUTING.md).
- [ ] This pull request will be closed if I failed to update it even once in a week.

### CODE REVIEW

**Comment by anshumanv** [comment]
This looks totally amazing! 😄 
Please add more content, if convenient.

**Review by anshumanv — APPROVED** [review]
👍

**Comment by anshumanv** [comment]
😍, btw don't feel shy to star the repo 😛 

lel

**Comment by aulisius** [comment]
Haha. Done. Thanks for merging :) . And a really useful project.

**Comment by anshumanv** [comment]
Expecting more such quality content from you then. 😆

**Pull request merged**
