### PR TITLE
Using <kbd> in place of images

### LINKED ISSUE #297: Using <kbd> in place of images in README
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This issue is for enhancement/bug fixing.
- [ ] This issue is an addition to JSON database.
- [x] I have gone through [Contribution Guidelines](https://github.com/anshumanv/ongaku/blob/master/CONTRIBUTING.md).
- [x] Assign this issue to me.

### PR DESCRIPTION
**Pull request by aashutoshrathi**
I just learned about <kbd> kbd</kbd> hence removing clutter in README rendering
Reverting my own commits 😜

Fixes #297

Demo: https://ongaku-298.surge.sh

#### This PR is for README.md.
- [ ] This issue is for enhancement/bug fixing.
- [ ] This issue is an addition to JSON database.
	- [ ] Pull Request Title is of form `Added [Anime Name]`.
- [ ] This addition is already on ongaku.
	- [ ] This PR is an improvement to current addition.
- [x] I have checked my addition locally and it is working and won't break existing entries.
- [x] I have gone through [Contribution Guidelines](https://github.com/anshumanv/ongaku/blob/master/CONTRIBUTING.md).
- [x] This pull request will be closed if I failed to update it even once in a week.

## Diff Preview

image

### CODE REVIEW

**Comment by aashutoshrathi** [comment]
@anshumanv @starkblaze01 Please review n00b changes.

**Comment by anshumanv** [comment]
No change is noob 🙏

**Review by anshumanv — APPROVED** [review]
Thankss Jirennn 🙏

**Comment by aashutoshrathi** [comment]
@anshumanv Auto surge deployments not working now?

**Comment by anshumanv** [comment]
Hm unusual, I haven't used them in a while, seems like they don't work

**Comment by anshumanv** [comment]
No worries, I'll add netlify, we can clear up the travis file.

**Pull request merged**
