### PR TITLE
Added [One Punch Man] Theme and Opening

### PR DESCRIPTION
**Pull request by 123survesh**
Fixes #{195}

#### This PR is for [One Punch Man].

- [ ] This issue is for enhancement/bug fixing.
- [x] This issue is an addition to JSON database.
	- [x] Pull Request Title is of form `Added [Anime Name]`.
- [ ] This addition is already on ongaku.
	- [ ] This PR is an improvement to current addition.
- [x] I have checked my addition locally and it is working and won't break existing entries.
- [x] I have gone through [Contribution Guidelines](https://github.com/anshumanv/ongaku/blob/master/CONTRIBUTING.md).
- [ ] This pull request will be closed if I failed to update it even once in a week.

### CODE REVIEW

**Comment by anshumanv** [comment]
Hey, @123survesh thanks for your contribution. 😄

**Review by anshumanv — CHANGES_REQUESTED** [review]
Please add new additions at the end of each section.

**Comment by 123survesh** [comment]
Hi @anshumanv ,
I have added them to the end of their respective subgroups.

**Comment by anshumanv** [comment]
Please try to maintain the indentation from next point on.

**Review by anshumanv — APPROVED** [review]

**Pull request merged**
