### PR TITLE
Remove Close Tracklist

### LINKED ISSUE #217: Remove the close button on tracklist and fixed search on top
To remove the close button on tracklist because we can just click outside to close it now and the close button isn't even fixed on top to close anytime. 
Fixed search input on top so that you can search anywhere on tracklist.

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This issue is for enhancement/bug fixing.
- [ ] This issue is an addition to JSON database.
- [x] I have gone through [Contribution Guidelines](https://github.com/anshumanv/ongaku/blob/master/CONTRIBUTING.md).
- [x] Assign this issue to me.

### PR DESCRIPTION
**Pull request by ong-yy**
Fixes #217 

To remove close button on tracklist and fix the position of search on top of tracklist.

- [x] This issue is for enhancement/bug fixing.
- [ ] This issue is an addition to JSON database.
	- [ ] Pull Request Title is of form `Added [Anime Name]`.
- [ ] This addition is already on ongaku.
	- [ ] This PR is an improvement to current addition.
- [x] I have checked my addition locally and it is working and won't break existing entries.
- [x] I have gone through [Contribution Guidelines](https://github.com/anshumanv/ongaku/blob/master/CONTRIBUTING.md).
- [x] This pull request will be closed if I failed to update it even once in a week.

### CODE REVIEW

**Comment by anshumanv** [comment]
The search bar is not functioning, also please add commits to this PR itself to undo hide close button so the entire issue is solved in one go.

**Comment by ong-yy** [comment]
So is the close button fix to the top together with the search bar?

**Comment by anshumanv** [comment]
No close button will stay at the top and will disappear if the user scrolls, if the user scrolls only search bar will stay fixed.

**Comment by ong-yy** [comment]
@anshumanv, I has made the changes again. Please check on it and tell me how is it. Thank you.

**Comment by anshumanv** [comment]
@YernYee thanks for the quick fix, but what I need is the close button should be at the top and the search bar below it (no changes in positions), as the user scrolls down everything will scroll, as the search bar touches the top of the window it stays put there. Please do it this way.

**Comment by ong-yy** [comment]
@anshumanv. Oic.. Really sorry for the misunderstand. I'll fix it and inform you soon.

**Comment by ong-yy** [comment]
@anshumanv, finally it's done. Please review. Thank you.

**Comment by anshumanv** [comment]
@YernYee it works well, can you please look into why other commits crept in this PR?
* Make sure your master is even with upstream.
* create a different branch from master.
* add commits to that branch.
* push that branch and send PR

**Pull request closed without merging**
